# Generated by Django 6.1 on 2026-08-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='current_vote',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pokerroom',
            name='deck',
            field=models.CharField(default='0,1,2,3,5,8,13,21,34,55,89,?,Coffee', max_length=100),
        ),
        migrations.AddField(
            model_name='pokerroom',
            name='voting_status',
            field=models.CharField(choices=[('voting', 'Voting'), ('revealed', 'Revealed')], default='voting', max_length=20),
        ),
    ]
