# Generated by Django 6.1 on 2026-08-25

import django.db.models.deletion
import rooms.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0005_alter_issue_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="current_vote",
            field=models.CharField(
                blank=True,
                help_text="The value voted. Set to null if they haven't voted or retracted their vote.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="guest_token",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=rooms.utils.generate_guest_token,
                help_text="Session-linked token for tracking guest identities without user accounts.",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked user account, if the participant is registered.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="pokerroom",
            name="owner",
            field=models.ForeignKey(
                help_text="The user who created and facilitates the room.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="pokerroom",
            name="public_id",
            field=models.CharField(
                db_index=True,
                default=rooms.utils.generate_public_id,
                help_text="Secure, unguessable ID used in sharing URLs.",
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="pokerroom",
            name="voting_status",
            field=models.CharField(
                choices=[("voting", "Voting"), ("revealed", "Revealed")],
                default="voting",
                help_text="Controls the privacy of votes. If 'voting', votes are hidden from clients.",
                max_length=20,
            ),
        ),
    ]
