# Generated by Django 6.1 on 2026-08-25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0006_alter_participant_current_vote_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="connection_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
