# Generated by Django 6.1 on 2026-08-25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0007_participant_connection_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="last_reminded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
