# Generated by Django 6.1 on 2026-08-27 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_participant_last_reminded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='avatar',
            field=models.CharField(blank=True, choices=[('sereno', 'Sereno'), ('contento', 'Contento'), ('pillo', 'Pillo'), ('dormilon', 'Dormilón')], help_text='Cosmetic face drawn on the seat. Blank means derive one.', max_length=20),
        ),
        migrations.AddField(
            model_name='participant',
            name='color_index',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Index into the seat palette. Null means derive one.', null=True, validators=[django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AddField(
            model_name='participant',
            name='pet',
            field=models.CharField(blank=True, choices=[('gato', 'Gato'), ('perro', 'Perro'), ('axolote', 'Axolote'), ('capibara', 'Capibara'), ('dragon', 'Dragón'), ('rana', 'Rana')], help_text='Cosmetic companion drawn beside the seat. Blank means derive one.', max_length=20),
        ),
    ]
