# Generated by Django 6.1 on 2026-08-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_participant_avatar_participant_color_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='last_throw_at',
            field=models.DateTimeField(blank=True, help_text='Cooldown anchor for the playful layer.', null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='throws_this_round',
            field=models.PositiveSmallIntegerField(default=0, help_text='Per-round throw count. Reset with the votes; never accumulates.'),
        ),
        migrations.AddField(
            model_name='pokerroom',
            name='allow_playful_actions',
            field=models.BooleanField(default=True, help_text='Facilitator switch for the playful layer across the whole room.'),
        ),
    ]
