# Generated by Django 6.1 on 2026-08-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_participant_last_throw_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokerroom',
            name='recess_open',
            field=models.BooleanField(default=False, help_text='Whether people can leave their seats and walk around. Only meaningful while voting; closed automatically on reveal. Positions are never stored.'),
        ),
    ]
